### PR TITLE
Start

### PR DESCRIPTION
**Pull request by gfr10598**
Just experimenting

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server-go/16)

### CODE REVIEW

**Comment by bassosimone** [comment]
Review status: 0 of 10 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[ndt-server.go, line 66 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNQdIALNlTYtI0R9K:-L4pNQdIALNlTYtI0R9L:b-70g6ef) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/ndt-server.go#L66)):*
> ```Go
> 
> func main() {
> 	// TODO - does this listen on both ipv4 and ipv6?
> ```

I tested this locally. It's IPv4 only

---

*[protocol/protocol.go, line 28 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNhRrws_VOFLMjiAD:-L4pNhRrws_VOFLMjiAE:b-4izno) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L28)):*
> ```Go
> const (
> 	// TestMid and other enums indicate the individual tests.
> 	TestMid TestCode = 1 << iota
> ```

I assume that `1 << iota` is such that go understands that these are bit fields

---

*[protocol/protocol.go, line 44 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNv4D6Kx-TKC8ANTb:-L4pNv4D6Kx-TKC8ANTc:b-qthppa) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L44)):*
> ```Go
> type Message struct {
> 	// Header contains the message type and length
> 	Header header
> ```

Does this mean that the header is opaque from outside the module?

---

*[protocol/protocol.go, line 52 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pO-keqk1JVgFz2AIF:-L4pO-keqk1JVgFz2AIG:b-tc4hoe) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L52)):*
> ```Go
> // not conform to the binary protocol, e.g. when WebSockets
> // is used.
> var IllegalMessage = errors.New("Illegal Message Header")
> ```

I think this should be `ErrIllegalMessage`

---

*[protocol/protocol.go, line 55 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pO7w6iRo67MnS-le2:-L4pO7w6iRo67MnS-le3:bmpaplv) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L55)):*
> ```Go
> 
> func ReadMessage(rdr io.Reader) (Message, error) {
> 	brdr := bufio.NewReader(rdr)
> ```

It is not clear to me what chaining (buffered?) readers does. If there is data left in buffer after this function returns, where will such data go? (I think in general a NDT client may not send back to back messages, but perhaps it would be more robust to have a single buffered reader wrapping the connection for its whole lifetime

---

*[protocol/protocol.go, line 61 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pObelPHRm_-L8PeVP:-L4pObelPHRm_-L8PeVQ:b-5ukuxp) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L61)):*
> ```Go
> 		return Message{}, err
> 	}
> 	if get[0] > 11 {
> ```

This is not totally clear to me. What case is this? (Maybe a comment would help) - ah, is this extended?

---

*[protocol/protocol.go, line 127 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pP0biOZBvdqXbhijG:-L4pP0biOZBvdqXbhijH:b-siqte9) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L127)):*
> ```Go
> 		}
> 		return Login{byte(tests), lj.Msg, true}, nil
> 	default:
> ```

Do we want to panic here?

---

*[protocol/protocol_test.go, line 1 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPMhriR0Ak9QU9JFC:-L4pPMhriR0Ak9QU9JFD:b-r6r5jt) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L1)):*
> ```Go
> package protocol_test
> ```

Ah, I notice that I was not using this pattern of `${module}_test` in my code

---

*[protocol/protocol_test.go, line 11 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPKqt9lLTx7nSxW9s:-L4pPKqt9lLTx7nSxW9t:b8vzsfi) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L11)):*
> ```Go
> )
> 
> func init() {
> ```

Is this called automatically?

---

*[protocol/protocol_test.go, line 16 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPTtdWbp7fqXZhg3v:-L4pPTtdWbp7fqXZhg3w:brqvn0y) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L16)):*
> ```Go
> }
> 
> func TestReadMessage(t *testing.T) {
> ```

I think, for robustness, the reader should be capable of reading many back to back messages without issues

---

*[protocol/protocol_test.go, line 27 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPbT1v7hySqNj5Ypl:-L4pPbT1v7hySqNj5Ypm:bm1ztn6) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L27)):*
> ```Go
> 		return
> 	}
> 	if len(msg.Content) != 33 {
> ```

Maybe 33 can be a constant?

---

*[tcpinfo/tcpinfo_linux.go, line 30 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPznF6gecFr1Utg5D:-L4pPznF6gecFr1Utg5E:b-zhvxbs) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/tcpinfo/tcpinfo_linux.go#L30)):*
> ```Go
> 
> // SetMSS uses syscall to set the MSS value on a connection.
> func SetMSS(tcp *net.TCPListener, mss int) {
> ```

Maybe not so important, but I think this may even work on Darwin, no?

---

*[tests/middlebox.go, line 28 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pQMVlhyyWYzj7cbAR:-L4pQMVlhyyWYzj7cbAS:b-7m27qm) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/tests/middlebox.go#L28)):*
> ```Go
> func DoMiddleBox(conn net.Conn) {
> 	// Handle the MiddleBox test.
> 	addr, _ := net.ResolveTCPAddr("tcp", "localhost:0")
> ```

Again, here, I think this may not listen on ipv6 (based on the fact that the code that I run locally was not listening on ipv6)

---

*[tests/middlebox.go, line 50 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pQdhvX6FRnPKc8lWt:-L4pQdhvX6FRnPKc8lWu:b3ly6jr) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/tests/middlebox.go#L50)):*
> ```Go
> 	if err != nil {
> 		log.Println("Error accepting: ", err.Error())
> 		// TODO - should this be fatal?
> ```

I think it should not. Maybe in such case the server should just abort the whole test?

---

*[tests/middlebox.go, line 59 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pQxOoljxqN4eX7IAq:-L4pQxOoljxqN4eX7IAr:bkoe01k) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/tests/middlebox.go#L59)):*
> ```Go
> 	start := time.Now()
> 	count := 0
> 	// This deadline actually controls the send period.
> ```

(This is a nice example of why deadlines are more useful than timeout sometimes :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16)*

**Comment by bassosimone** [comment]
Review status: 0 of 10 files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pRRbnzJg8PdAun-Zd:-L4pRRbnzJg8PdAun-Ze:bqrxgt6) (no related file):*
(There also seems to be a small conflict with master.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16)*

**Comment by bassosimone** [comment]
Oh, and @gfr10598, additionally:

- [it seems that tests are not passing](https://travis-ci.org/m-lab/ndt-server-go/jobs/335226065#L499)

- travis is clearly using IPv6 in the above comment, so perhaps my system is not-so-ipv6-friendly?

**Comment by bassosimone** [comment]
Review status: 0 of 10 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L58Q6UmjHAVH8QTE6Lv:-L58Q6UmjHAVH8QTE6Lw:b5nqa3w) (no related file):*
I was thinking that it would be nice to just take the tcp_info bits, perhaps move tcp_info into the netx package that was just created, and submit just tcp_info as a PR. Makes sense?

After that, I was thinking that perhaps it would make sense to have a small PR on messages reading. I also have botticelli code that does that, and there is new netx code. So, it seems to me some work is needed to sync up the code reading messages, by aligning your code and botticelli's one. The two main differences are: the lifecycle of the buffered reader, that in botticelli spans the lifetime of the whole connection, and the usage of timed out I/O.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16)*

**Comment by gfr10598** [comment]
Review status: 0 of 8 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pRRbnzJg8PdAun-Zd:-L5so7F-Lgi5lA0F5LSX:bnlamz5) (no related file):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

(There also seems to be a small conflict with master.)
</blockquote></details>

resolved.

---

*[a discussion](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L58Q6UmjHAVH8QTE6Lv:-L5sncd885UOYNQMp7uh:b-knj0sg) (no related file):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I was thinking that it would be nice to just take the tcp_info bits, perhaps move tcp_info into the netx package that was just created, and submit just tcp_info as a PR. Makes sense?

After that, I was thinking that perhaps it would make sense to have a small PR on messages reading. I also have botticelli code that does that, and there is new netx code. So, it seems to me some work is needed to sync up the code reading messages, by aligning your code and botticelli's one. The two main differences are: the lifecycle of the buffered reader, that in botticelli spans the lifetime of the whole connection, and the usage of timed out I/O.
</blockquote></details>

This SGTM.  I'll pull out the tcp_info into a new PR.  Let's talk about how to merge best of multi-message reader and protocol.go.

---

*[ndt-server.go, line 66 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNQdIALNlTYtI0R9K:-L5sn_xm6bCprvCnOoaT:bq5wuc9) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/ndt-server.go#L66)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I tested this locally. It's IPv4 only
</blockquote></details>

Updated comment.

---

*[protocol/protocol.go, line 28 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNhRrws_VOFLMjiAD:-L5sgiByZExhxs4K7BGl:br24jsl) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L28)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I assume that `1 << iota` is such that go understands that these are bit fields
</blockquote></details>

Yes.  iota is shorthand for value that increments by one, but it is worth looking at the golang documentation.

---

*[protocol/protocol.go, line 44 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNv4D6Kx-TKC8ANTb:-L5sgzdrZ4oY-gXXV8aX:bt6b8bw) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L44)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Does this mean that the header is opaque from outside the module?
</blockquote></details>

Yes.  May want to change that - not sure yet.

---

*[protocol/protocol.go, line 52 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pO-keqk1JVgFz2AIF:-L5sh33kmyG66WHesNoi:b-afbb6s) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L52)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I think this should be `ErrIllegalMessage`
</blockquote></details>

Yup.  Need to run lint.

---

*[protocol/protocol.go, line 55 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pO7w6iRo67MnS-le2:-L5sismtlZVCTH0sockS:b-19h3z) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L55)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

It is not clear to me what chaining (buffered?) readers does. If there is data left in buffer after this function returns, where will such data go? (I think in general a NDT client may not send back to back messages, but perhaps it would be more robust to have a single buffered reader wrapping the connection for its whole lifetime
</blockquote></details>


Agree.  Added comment to  replace this.

---

*[protocol/protocol.go, line 127 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pP0biOZBvdqXbhijG:-L5sjLbqBF38WEYbDQgw:bwhjdig) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L127)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Do we want to panic here?
</blockquote></details>

Moved up the error, to make it clearer.

---

*[protocol/protocol_test.go, line 1 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPMhriR0Ak9QU9JFC:-L5sjxva3vFwza9_wldP:b-obqa5) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L1)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Ah, I notice that I was not using this pattern of `${module}_test` in my code
</blockquote></details>

There are two options:
  For whitebox testing, use the same module name, e.g. protocol
  For blackbox testing, use ${module}_test convention.
Prefer blackbox when possible, and consider separating into two files if you have both white and blackbox tests.

---

*[protocol/protocol_test.go, line 11 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPKqt9lLTx7nSxW9s:-L5skHpgnub6wajXfzTs:bb7867z) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L11)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Is this called automatically?
</blockquote></details>

Yup.

---

*[protocol/protocol_test.go, line 16 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPTtdWbp7fqXZhg3v:-L5skKybt4qpnPTNnzJ3:bb6sh2i) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L16)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I think, for robustness, the reader should be capable of reading many back to back messages without issues
</blockquote></details>

Ack.

---

*[protocol/protocol_test.go, line 27 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPbT1v7hySqNj5Ypl:-L5smGL2kqKEi994W8Fa:bpodft8) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L27)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Maybe 33 can be a constant?
</blockquote></details>

replaced with len(m)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16)*

**Comment by bassosimone** [comment]
Review status: 0 of 8 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[ndt-server.go, line 66 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNQdIALNlTYtI0R9K:-L5t8IhxLu5Kkrcwl3Kk:b-jp80b4) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/ndt-server.go#L66)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Updated comment.
</blockquote></details>

FWIW, I tested this also on Linux inside Windows obtaining same behavior.

---

*[protocol/protocol.go, line 28 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNhRrws_VOFLMjiAD:-L5t8Utlr5QF7YrpIzYR:b2nhktc) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L28)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Yes.  iota is shorthand for value that increments by one, but it is worth looking at the golang documentation.
</blockquote></details>

OK!

---

*[protocol/protocol.go, line 44 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pNv4D6Kx-TKC8ANTb:-L5t8Y_RpQidvynfMXH3:b2nhktc) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L44)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Yes.  May want to change that - not sure yet.
</blockquote></details>

OK!

---

*[protocol/protocol.go, line 52 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pO-keqk1JVgFz2AIF:-L5t8_4Z58DuPlHNWXCj:b2nhktc) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L52)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Yup.  Need to run lint.
</blockquote></details>

OK!

---

*[protocol/protocol.go, line 55 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pO7w6iRo67MnS-le2:-L5t8b2H3DNmK8h-Zdws:bfrkzmz) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L55)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Agree.  Added comment to  replace this.
</blockquote></details>

FYI this is what I tried to implement in https://github.com/m-lab/ndt-server-go/pull/21 (there is your unmodified code and another commit with my changes).

---

*[protocol/protocol.go, line 127 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pP0biOZBvdqXbhijG:-L5t8uhWr4pVphcPq_Bm:b-u26r08) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol.go#L127)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Moved up the error, to make it clearer.
</blockquote></details>

FYI here I _think_ the `return Login{` line should have `err` rather than `nil` as last argument, otherwise a `strconv.Atoi` error is swallowed (noticed yesterday when was trying to write unit tests for the code).

---

*[protocol/protocol_test.go, line 1 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPMhriR0Ak9QU9JFC:-L5t97dq3h_j8geV1iRD:bwsvfmy) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L1)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

There are two options:
  For whitebox testing, use the same module name, e.g. protocol
  For blackbox testing, use ${module}_test convention.
Prefer blackbox when possible, and consider separating into two files if you have both white and blackbox tests.
</blockquote></details>

OK, thanks! I'll stick to the blackbox convention then!

---

*[protocol/protocol_test.go, line 11 at r4](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16#-L4pPKqt9lLTx7nSxW9s:-L5t9BciSDBxnPxdFf2G:b-8mxhzd) ([raw file](https://github.com/m-lab/ndt-server-go/blob/1271f367d38c18d3a6177927aff16494ccb5bb5b/protocol/protocol_test.go#L11)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Yup.
</blockquote></details>

OK! (cool !)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16)*

**Comment by bassosimone** [comment]
Reviewed 1 of 5 files at r1, 2 of 5 files at r2, 1 of 1 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/16)*

**Comment by gfr10598** [comment]
Obsolete.

**Pull request closed without merging**
