### PR TITLE
feature(travis): run golint and go test

### PR DESCRIPTION
**Pull request by bassosimone**
With this diff I start adding support for CI. I currently do not have
enough privileges to enable travis for the repository, tho.

This is only the start (i.e., what I run locally: go lint and go test); we
can do more in the future, especially computing coverage.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server-go/19)

### CODE REVIEW

**Comment by gfr10598** [comment]
:lgtm:
I also enabled travis.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/19#-:-L41BH5wotkUFBaJ24z3:buxplpd)*

**Comment by bassosimone** [comment]
Merged master after #18 into this branch.

**Comment by bassosimone** [comment]
@gfr10598 it seems we don't have the permission to pull in the `travis` subrepo: https://travis-ci.org/m-lab/ndt-server-go/jobs/334795225#L433

I would assume this is because the repository is not public?

**Comment by bassosimone** [comment]
Merging!

**Pull request merged**
