### PR TITLE
protocol.go: import botticelli constants

### PR DESCRIPTION
**Pull request by bassosimone**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server-go/24)

### CODE REVIEW

**Comment by gfr10598** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[protocol/protocol.go, line 25 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kiGp54kJBp6_V6hSm:-L9kiGp54kJBp6_V6hSn:b-uw5h5p) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L25)):*
> ```Go
> // the `Msg` prefix to all messages not having it for clarity. Also, the
> // TEST_MSG define is mapped onto the MsgTest constant.
> ```

Remove blank line here and below "Test identifiers"

---

*[protocol/protocol.go, line 68 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kMyz8Caj596fmkIBd:-L9kMyz8Caj596fmkIBe:b9u4pbc) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L68)):*
> ```Go
> 	// TestMeta indicate that we will send metadata.
> 	TestMeta
> 	// TestC2SExt is the multi stream upload test.
> ```

Rather than adding more codes, I'm leaning toward providing new services on a different port or a different handler path through http/https/ws.

---

*[protocol/protocol.go, line 75 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kiMM5D2ivyIP8cssd:-L9kiMM5D2ivyIP8csse:b-30o0vi) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L75)):*
> ```Go
> 
> // Queue states returned to client:
> ```

Another blank line.  My impression is that in golang the white space is significant for documentation comments, so generally there is no space between comment and the block it applies to.  If you find otherwise please let me know.

---

*[protocol/protocol.go, line 116 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kNTAi7502wbF7OmMC:-L9kNTAi7502wbF7OmMD:b-6xpcpl) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L116)):*
> ```Go
> 		return Message{}, err
> 	}
> 	if get[0] > MsgExtendedLogin {
> ```

I'd like to initially not even implement that binary legacy interface, in other words, NOT make this backward compatible with the old server.  Is that ok with you?  If we do implement both, it would be good to do it on separate ports.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24)*

**Comment by bassosimone** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[protocol/protocol.go, line 68 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kMyz8Caj596fmkIBd:-LAIZN7_09ipriyZlxeN:b-90lnqa) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L68)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Rather than adding more codes, I'm leaning toward providing new services on a different port or a different handler path through http/https/ws.
</blockquote></details>

The codes I am adding here are actually supported by the NDT spec (i.e. they are not new codes rather codes that were missing from the enumeration of _all_ codes).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24)*

**Comment by bassosimone** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[protocol/protocol.go, line 25 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kiGp54kJBp6_V6hSm:-LAIZjot2tIIzzvZtM6c:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L25)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Remove blank line here and below "Test identifiers"
</blockquote></details>

Done.

---

*[protocol/protocol.go, line 75 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kiMM5D2ivyIP8cssd:-LAIZmtQ0gdyf00QVyCv:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L75)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Another blank line.  My impression is that in golang the white space is significant for documentation comments, so generally there is no space between comment and the block it applies to.  If you find otherwise please let me know.
</blockquote></details>

Done.

---

*[protocol/protocol.go, line 116 at r1](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24#-L9kNTAi7502wbF7OmMC:-LAIZnm-7HL1WtTFNMqs:b-vroq93) ([raw file](https://github.com/m-lab/ndt-server-go/blob/3ce29b3efc3b6d2e6f47762686e387a232e9fede/protocol/protocol.go#L116)):*
> If we do implement both, it would be good to do it on separate ports.

Yeah, I think we need to implement _at least_ what MK supports (i.e. binary messages with JSON encoded values inside). We can avoid implementing the legacy legacy stuff and we can make things more pleasant for new clients.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/24)*

**Comment by gfr10598** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[protocol/protocol.go, line 73 at r2](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-LAsEl3zD0l1wKrU16A4:-LAsEl3zD0l1wKrU16A5:b-j8rs4n) ([raw file](https://github.com/m-lab/ndt-server-go/blob/2de950d0204d636fe241908e62a7c95bcd1529ea/protocol/protocol.go#L73)):*
> ```Go
> 
> // Queue states returned to client:
> const (
> ```

Annoying that we are stuck with string numbers, but I guess we need this for backward compatibility with clients.

---

*[protocol/protocol.go, line 166 at r2](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-LAsDqOU8De_8-CtsowA:-LAsDqOU8De_8-CtsowB:bsdb2ny) ([raw file](https://github.com/m-lab/ndt-server-go/blob/2de950d0204d636fe241908e62a7c95bcd1529ea/protocol/protocol.go#L166)):*
> ```Go
> 
> 	default:
> 		// FALLTHROUGH
> ```

// Log an error message?

---

*[protocol/protocol.go, line 168 at r2](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-LAsEGAQ-KDNq_1DlLVV:-LAsEGAQ-KDNq_1DlLVW:b-h4cs8l) ([raw file](https://github.com/m-lab/ndt-server-go/blob/2de950d0204d636fe241908e62a7c95bcd1529ea/protocol/protocol.go#L168)):*
> ```Go
> 		// FALLTHROUGH
> 	}
> 	return Login{}, errors.New("unhandled message type")
> ```

move into default

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-:-LAsF7kGDVdDTsXP5h4a:bnfp4nl)*

**Comment by bassosimone** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[protocol/protocol.go, line 73 at r2](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-LAsEl3zD0l1wKrU16A4:-LAsyxkCDHpl_ZWVIVjC:bb77u1k) ([raw file](https://github.com/m-lab/ndt-server-go/blob/2de950d0204d636fe241908e62a7c95bcd1529ea/protocol/protocol.go#L73)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Annoying that we are stuck with string numbers, but I guess we need this for backward compatibility with clients.
</blockquote></details>

Yeah

---

*[protocol/protocol.go, line 166 at r2](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-LAsDqOU8De_8-CtsowA:-LAszsyA9xt_4abOYdMF:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/2de950d0204d636fe241908e62a7c95bcd1529ea/protocol/protocol.go#L166)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

// Log an error message?
</blockquote></details>

Done.

---

*[protocol/protocol.go, line 168 at r2](https://reviewable.io/reviews/m-lab/ndt-server-go/24#-LAsEGAQ-KDNq_1DlLVV:-LAszt_DCeV43RiTtfuY:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/2de950d0204d636fe241908e62a7c95bcd1529ea/protocol/protocol.go#L168)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

move into default
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server-go/24)*

**Pull request merged**
