### PR TITLE
just tcp_info

### PR DESCRIPTION
**Pull request by gfr10598**
tcp_info related code, pulled from larger PR.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/ndt-server-go/22)

### CODE REVIEW

**Comment by bassosimone** [comment]
Reviewed 1 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tcpinfo/tcpinfo_darwin.go, line 9 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tDVBW_CEYiE8lwnuV:-L5tDVBW_CEYiE8lwnuW:b-pqae9z) ([raw file](https://github.com/m-lab/ndt-server-go/blob/6737f53a61e52038c886217441a805de3b114893/tcpinfo/tcpinfo_darwin.go#L9)):*
> ```Go
> // Alternate (better) way to get tcpinfo
> func TCPInfo2(conn *net.TCPConn) (string, error) {
> 	return "No TCPInfo", nil
> ```

I admin I didn't think too much about usage, still I find returning a string rather than a struct inconsistent with the Linux API. Also, not returning error seems a bit strange. It may perhaps be better to return the Go equivalent of `EPROTOOPT`, isn't it?

---

*[tcpinfo/tcpinfo_linux.go, line 15 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tEvc3ykzB97LmRSLk:-L5tEvc3ykzB97LmRSLl:b2086g9) ([raw file](https://github.com/m-lab/ndt-server-go/blob/6737f53a61e52038c886217441a805de3b114893/tcpinfo/tcpinfo_linux.go#L15)):*
> ```Go
> func TCPInfo2(conn *net.TCPConn) (syscall.TCPInfo, error) {
> 	var info syscall.TCPInfo
> 	file, err := conn.File()
> ```

I think here should probably `defer file.Close()`, no?

---

*[tcpinfo/tcpinfo_linux.go, line 23 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tEZCx9la0aWkbLdua:-L5tEZCx9la0aWkbLdub:b-3dw6ss) ([raw file](https://github.com/m-lab/ndt-server-go/blob/6737f53a61e52038c886217441a805de3b114893/tcpinfo/tcpinfo_linux.go#L23)):*
> ```Go
> 
> 	infoLen := uint32(syscall.SizeofTCPInfo)
> 	if _, _, e1 := syscall.Syscall6(syscall.SYS_GETSOCKOPT, fd, syscall.SOL_TCP, syscall.TCP_INFO, uintptr(unsafe.Pointer(&info)), uintptr(unsafe.Pointer(&infoLen)), 0); e1 != 0 {
> ```

Maybe here you can wrap this line, which is very long?

---

*[tcpinfo/tcpinfo_linux.go, line 30 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tEe9_6Ztn_mfLCzNS:-L5tEe9_6Ztn_mfLCzNT:bv4327l) ([raw file](https://github.com/m-lab/ndt-server-go/blob/6737f53a61e52038c886217441a805de3b114893/tcpinfo/tcpinfo_linux.go#L30)):*
> ```Go
> 
> // SetMSS uses syscall to set the MSS value on a connection.
> func SetMSS(tcp *net.TCPListener, mss int) {
> ```

Perhaps we should return error rather than calling `Exit`?

---

*[tcpinfo/tcpinfo_linux.go, line 37 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tF-6cs-EXJ-U8UtMa:-L5tF-6cs-EXJ-U8UtMb:b-x9nine) ([raw file](https://github.com/m-lab/ndt-server-go/blob/6737f53a61e52038c886217441a805de3b114893/tcpinfo/tcpinfo_linux.go#L37)):*
> ```Go
> 	}
> 	err = syscall.SetsockoptInt(int(file.Fd()), syscall.SOL_TCP, syscall.TCP_MAXSEG, mss)
> 	file.Close()
> ```

If I'm right and a `defer file.Close()` is needed above, I'd `defer` also here for uniformity

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22)*

**Comment by bassosimone** [comment]
BTW I do not immediately understand what provokes [this crash](https://travis-ci.org/m-lab/ndt-server-go/jobs/344393131#L494).

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-:-L5tFii_3Y-3F8H4KBOE:b-xzdwie)*

**Comment by gfr10598** [comment]
I've removed 1.8.  It seems it doesn't support the :0 "choose a port" notation, and I wasn't checking the error.

---

Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[tcpinfo/tcpinfo_darwin.go, line 9 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tDVBW_CEYiE8lwnuV:-L8IjDCxnLe0wnprdYxJ:b-w82ea1) ([raw file](https://github.com/m-lab/ndt-server-go/blob/89ba4ee4536b11386a00aae26300ddc0a5281c01/tcpinfo/tcpinfo_darwin.go#L9)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I admin I didn't think too much about usage, still I find returning a string rather than a struct inconsistent with the Linux API. Also, not returning error seems a bit strange. It may perhaps be better to return the Go equivalent of `EPROTOOPT`, isn't it?
</blockquote></details>

Changed interface a bit.  Better?

---

*[tcpinfo/tcpinfo_linux.go, line 15 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tEvc3ykzB97LmRSLk:-L8Igh87kSSBT7CYwjVZ:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/89ba4ee4536b11386a00aae26300ddc0a5281c01/tcpinfo/tcpinfo_linux.go#L15)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

I think here should probably `defer file.Close()`, no?
</blockquote></details>

Done.

---

*[tcpinfo/tcpinfo_linux.go, line 23 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tEZCx9la0aWkbLdua:-L8Iggjvf16xxsO0e-vG:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/89ba4ee4536b11386a00aae26300ddc0a5281c01/tcpinfo/tcpinfo_linux.go#L23)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Maybe here you can wrap this line, which is very long?
</blockquote></details>

Done.

---

*[tcpinfo/tcpinfo_linux.go, line 30 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tEe9_6Ztn_mfLCzNS:-L8IgoaVugGlNngJ-iqs:bwj0xux) ([raw file](https://github.com/m-lab/ndt-server-go/blob/89ba4ee4536b11386a00aae26300ddc0a5281c01/tcpinfo/tcpinfo_linux.go#L30)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

Perhaps we should return error rather than calling `Exit`?
</blockquote></details>

Done.
I tend to take shortcuts and clean them up later.

---

*[tcpinfo/tcpinfo_linux.go, line 37 at r3](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-L5tF-6cs-EXJ-U8UtMa:-L8Igx8SguDs_xuNEW98:b-896fix) ([raw file](https://github.com/m-lab/ndt-server-go/blob/89ba4ee4536b11386a00aae26300ddc0a5281c01/tcpinfo/tcpinfo_linux.go#L37)):*
<details><summary><i>Previously, bassosimone (Simone Basso) wrote…</i></summary><blockquote>

If I'm right and a `defer file.Close()` is needed above, I'd `defer` also here for uniformity
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/ndt-server-go/22#-:-L8IlH_DGwKggrIjX77r:b6e3hbk)*

**Comment by bassosimone** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tcpinfo/tcpinfo_darwin.go, line 9 at r3](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/22#-L5tDVBW_CEYiE8lwnuV:-L8TggDO8tnoXjIt_yWy:bb77rdq) ([raw file](https://github.com/m-lab/ndt-server-go/blob/89ba4ee4536b11386a00aae26300ddc0a5281c01/tcpinfo/tcpinfo_darwin.go#L9)):*
<details><summary><i>Previously, gfr10598 (Gregory Russell) wrote…</i></summary><blockquote>

Changed interface a bit.  Better?
</blockquote></details>

Yap!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/ndt-server-go/22#-:-L8ThO-h897gyRSMJWpP:bnfp4nl)*

**Review by bassosimone — APPROVED** [review]
:whale:

**Pull request merged**
